version: "3.5"

services:

  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    restart: always

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=twitter-analyzer
      - MYSQL_USER=twitter
      - MYSQL_PASSWORD=twitter      
    restart: always
